steps:
  # 1. Build da imagem Docker usando o Dockerfile do GitHub salvando como :latest
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'southamerica-east1-docker.pkg.dev/lucky-era-497723-q0/imagens-node/qr-pets:latest', 
      '.'
    ]

  # 2. Envia a imagem :latest para o Artifact Registry do Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/lucky-era-497723-q0/imagens-node/qr-pets:latest']

images:
  - 'southamerica-east1-docker.pkg.dev/lucky-era-497723-q0/imagens-node/qr-pets:latest'

# CORREÇÃO DO ERRO ANTERIOR DE LOGS:
options:
  logging: CLOUD_LOGGING_ONLY